#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /usr/sbin/brctl ] || [ ! -x /sbin/vconfig ] ; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/brctl
copy_exec /sbin/vconfig
